version: '3'
services:
  nifi:
    image: apache/nifi:1.17.0
    container_name: nifi-1.17
    ports:
      - "9443:8443"
    environment:
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
      - NIFI_WEB_HTTPS_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=password12345678
      - NIFI_WEB_PROXY_HOST=localhost:9443,127.0.0.1:9443

    restart: unless-stopped
