version: '3'
services:
  nifi:
    image: apache/nifi:1.17.0
    container_name: nifi-1.17
    ports:
      - "9443:8443"
    environment:
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
      - NIFI_WEB_HTTPS_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=password12345678
      - NIFI_WEB_PROXY_HOST=localhost:9443,127.0.0.1:9443

    volumes:
      - ./conf:/opt/nifi/nifi-current/conf
      - ./logs:/opt/nifi/nifi-current/logs
      - ./state:/opt/nifi/nifi-current/state
      - ./provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./content_repository:/opt/nifi/nifi-current/content_repository
    restart: unless-stopped
